version: '3.9'

services:
  web:
    build: .
    container_name: psycho_app
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: psycho_app_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
